version: '3.8'

services:
  iot_api:
    build: .
    container_name: iot_api_modular
    restart: always
    ports:
      - "3100:3100"
    environment:
      - MONGO_URI=mongodb+srv://sims_grup_4_db_user:<grup42026>@cluster-iot-gps.9xi75ol.mongodb.net/
      
      - RASPBERRY_TUNNEL_URL=https://university-mud-picked-loaded.trycloudflare.com/actuator

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: iot_public_tunnel
    command: tunnel --url http://iot_api:3100
    depends_on:
      - iot_api